IF schema_id('kaoqin') IS NULL
    EXECUTE('CREATE SCHEMA [kaoqin]')
CREATE TABLE [kaoqin].[ChuChai] (
    [Id] [uniqueidentifier] NOT NULL,
    [UserId] [nvarchar](50),
    [Name] [nvarchar](50),
    [DepartmentId] [int] NOT NULL,
    [Department] [nvarchar](50),
    [Position] [nvarchar](50),
    [OutTime] [datetime] NOT NULL,
    [InTime] [datetime] NOT NULL,
    [OutPlace] [nvarchar](50),
    [OutReason] [nvarchar](250),
    [DepartmentOpinion] [nvarchar](150),
    [DepartmentOpinionApproverId] [nvarchar](50),
    [GeneralManagerOfficeOpinion] [nvarchar](150),
    [GeneralManagerOfficeOpinionApproverId] [nvarchar](50),
    [CompanyLeaderOpinion] [nvarchar](150),
    [CompanyLeaderOpinionApproverId] [nvarchar](150),
    [Status] [nvarchar](50),
    [Created] [datetime] NOT NULL,
    [Canceled] [datetime] NOT NULL,
    [Approved] [datetime] NOT NULL,
    CONSTRAINT [PK_kaoqin.ChuChai] PRIMARY KEY ([Id])
)
CREATE TABLE [kaoqin].[WaiQin] (
    [Id] [uniqueidentifier] NOT NULL,
    [UserId] [nvarchar](50),
    [Name] [nvarchar](50),
    [DepartmentId] [int] NOT NULL,
    [Department] [nvarchar](50),
    [Position] [nvarchar](50),
    [OutTime] [datetime] NOT NULL,
    [InTime] [datetime] NOT NULL,
    [OutPlace] [nvarchar](50),
    [OutReason] [nvarchar](250),
    [DepartmentOpinion] [nvarchar](150),
    [DepartmentOpinionApproverId] [nvarchar](50),
    [GeneralManagerOfficeOpinion] [nvarchar](150),
    [GeneralManagerOfficeOpinionApproverId] [nvarchar](50),
    [CompanyLeaderOpinion] [nvarchar](150),
    [CompanyLeaderOpinionApproverId] [nvarchar](150),
    [Status] [nvarchar](50),
    [Created] [datetime] NOT NULL,
    [Canceled] [datetime] NOT NULL,
    [Approved] [datetime] NOT NULL,
    CONSTRAINT [PK_kaoqin.WaiQin] PRIMARY KEY ([Id])
)
CREATE TABLE [kaoqin].[WeiDaKa] (
    [Id] [uniqueidentifier] NOT NULL,
    [UserId] [nvarchar](50),
    [Name] [nvarchar](50),
    [DepartmentId] [int] NOT NULL,
    [Department] [nvarchar](50),
    [Position] [nvarchar](50),
    [InputTime] [datetime] NOT NULL,
    [ActionTime] [datetime] NOT NULL,
    [Type] [nvarchar](50),
    [Reason] [nvarchar](250),
    [DepartmentOrCompanyOpinion] [nvarchar](150),
    [DepartmentOrCompanyOpinionApproverId] [nvarchar](50),
    [Status] [nvarchar](50),
    [Created] [datetime] NOT NULL,
    [Canceled] [datetime] NOT NULL,
    [Approved] [datetime] NOT NULL,
    CONSTRAINT [PK_kaoqin.WeiDaKa] PRIMARY KEY ([Id])
)
CREATE TABLE [kaoqin].[XiuJia] (
    [Id] [uniqueidentifier] NOT NULL,
    [UserId] [nvarchar](50),
    [Name] [nvarchar](50),
    [DepartmentId] [int] NOT NULL,
    [Department] [nvarchar](50),
    [Position] [nvarchar](50),
    [InputTime] [datetime] NOT NULL,
    [ActionStartTime] [datetime] NOT NULL,
    [ActionEndTime] [datetime] NOT NULL,
    [ActionDays] [decimal](18, 2) NOT NULL,
    [ActionHours] [decimal](18, 2) NOT NULL,
    [Type] [nvarchar](50),
    [Reason] [nvarchar](250),
    [DepartmentSupervisorOpinion] [nvarchar](150),
    [DepartmentSupervisorOpinionApproverId] [nvarchar](50),
    [DepartmentManagerOpinion] [nvarchar](150),
    [DepartmentManagerOpinionApproverId] [nvarchar](50),
    [CompanyLeaderOpinion] [nvarchar](150),
    [CompanyLeaderOpinionApproverId] [nvarchar](150),
    [Status] [nvarchar](50),
    [Created] [datetime] NOT NULL,
    [Canceled] [datetime] NOT NULL,
    [Approved] [datetime] NOT NULL,
    CONSTRAINT [PK_kaoqin.XiuJia] PRIMARY KEY ([Id])
)